<?php
// module/Usuario/view/Usuario/Usuario/delete.phtml:

$title = 'Delete Usuario';
$url   = $this->url('Usuario', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($Usuario->User) ?>" by
    "<?= $this->escapeHtml($Usuario->Email) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $Usuario->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>

