<?php
// module/Usuario/view/Usuario/Usuario/index.phtml:

$title = 'My Usuarios';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('Usuario', ['action' => 'add']) ?>">Add new Usuario</a>
</p>

<table class="table">
<tr>
    <th>User</th>
    <th>Email</th>
    <th>Contra</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($Usuarios as $Usuario) : ?>
    <tr>
        <td><?= $this->escapeHtml($Usuario->User) ?></td>
        <td><?= $this->escapeHtml($Usuario->Email) ?></td>
        <td><?= $this->escapeHtml($Usuario->Contra) ?></td>
        <td>
            <a href="<?= $this->url('Usuario', ['action' => 'edit', 'id' => $Usuario->id]) ?>">Edit</a>
            <a href="<?= $this->url('Usuario', ['action' => 'delete', 'id' => $Usuario->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

