<?php
// module/Usuarios/view/Usuarios/Usuarios/index.phtml:

$title = 'Mis Usuarios';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('Usuarios', ['action' => 'add']) ?>">Añadir Usuarios</a>
  <br>
    <a  href="<?= $this->url('application', ['action' => 'Index']) ?>">SALIR</a>
</p>

<table class="table">
<tr>
    <th>Usuario</th>
    <th>Email</th>
    <th>Contraseña</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($Usuarios as $Usuario) : ?>
    <tr>
        <td><?= $this->escapeHtml($Usuario->Usuario) ?></td>
        <td><?= $this->escapeHtml($Usuario->Email) ?></td>
        <td><?= $this->escapeHtml($Usuario->Contra) ?></td>
        <td>
            <a href="<?= $this->url('Usuarios', ['action' => 'edit', 'id' => $Usuario->id]) ?>">Edit</a>
            <a href="<?= $this->url('Usuarios', ['action' => 'delete', 'id' => $Usuario->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

